config/routes.rb
DaniTools::Application.routes.draw do

   resources            :users
   resources            :sessions, only: [:new, :create, :destroy]

   root                 to: 'static_pages#home'

   match '/help',       to: 'static_pages#help'
   match '/about',      to: 'static_pages#about'
   match '/contact',    to: 'static_pages#contact'

   match '/signup',     to: 'users#new'
   match '/signin',     to: 'sessions#new'
   match '/signout',    to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
   attr_accessible :email, :name, :password, :password_confirmation

   has_secure_password

   before_save { self.email.downcase! }
   before_save :create_remember_token

   validates :name,                    presence:   true,  
                                       length:     { maximum: 50 } 

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email,                   presence:   true, 
                                       format:     { with: VALID_EMAIL_REGEX }, 
                                       uniqueness: { case_sensitive: false }

   validates :password,                presence:   true,
                                       length:     { minimum: 6 }

   validates :password_confirmation,   presence:   true



   private

      def create_remember_token
         self.remember_token = SecureRandom.urlsafe_base64
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery
   include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

   def new
   end

   def create
      user = User.find_by_email(params[:session][:email])
      if user && user.authenticate(params[:session][:password])
         sign_in user
         redirect_back_or user
      else
         flash.now[:error] = "Invalid email/password combination"
         render 'new'
      end
   end

   def destroy
      sign_out
      redirect_to root_path
   end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

   def home
   end

   def help
   end

   def about
   end

   def contact 
   end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :signed_in_user,   only: [:index, :edit, :update, :destroy]
   before_filter :correct_user,     only: [:edit, :update]
   before_filter :admin_user,       only: :destroy

   def destroy
      user = User.find(params[:id])
      if current_user?(user)
         flash[:error] = "Don't delete yourself."
      else
         user.destroy
         flash[:success] = "User destroyed."
      end
      redirect_to users_path
   end

   def index
      if current_user.admin?
         @users = User.paginate(:page => params[:page], :per_page => 20)
      else
         redirect_to root_path
      end
   end

   def new
      if signed_in?
         redirect_to root_path
      else
         @user = User.new
      end
   end
   
   def show
      @user = User.find(params[:id])
   end

   def create
      if signed_in?
         redirect_to root_path
      else
         @user = User.new(params[:user])
         if @user.save
            sign_in @user
            flash[:success] = "Welcome to your tools collection, #{@user.name}."
            redirect_to @user
         else
            render 'new'
         end
      end
   end

   def edit
   end

   def update
      if @user.update_attributes(params[:user])
         flash[:success] = "Your profile is now updated."
         sign_in @user
         redirect_to @user
      else
         render 'edit'
      end
   end


   private

      def signed_in_user
         unless signed_in?
            store_location
            redirect_to signin_path, notice: "Please sign in." 
         end
      end

      def correct_user
         @user = User.find(params[:id])
         redirect_to(root_path) unless current_user?(@user)
      end

      def admin_user
         redirect_to(root_path) unless current_user.admin?
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

   def full_title(page_title)
      base_title = "My Tools Collection"
      if page_title.empty?
         base_title
      else
         "#{base_title} | #{page_title}"
      end
   end



end

app/helpers/sessions_helper.rb
module SessionsHelper

   def sign_in(user)
      cookies.permanent[:remember_token] = user.remember_token
      self.current_user = user
   end

   def signed_in?
      !current_user.nil?
   end

   def current_user=(user)
      @current_user = user
   end

   def current_user
      @current_user ||= User.find_by_remember_token(cookies[:remember_token])
   end

   def current_user?(user)
      user == current_user
   end
   
   def sign_out
      self.current_user = nil
      cookies.delete(:remember_token)
   end

   def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
   end

   def store_location
      session[:return_to] = request.fullpath
   end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

   # Gravatarpicture
   def gravatar_for(user)
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.name, class:"gravatar")
   end

end

app/views/layouts/_footer.html.erb
<footer id="footer_wrapper">
   <div id="footer">
      <p id="terminal">
         <%= "MyCollection: tools$ #{yield(:footer_title)}" %><br />
         <%= "MyCollection: tools$ " %><span id="cursor"></span>
      </p>
   </div>
   <div id="small_footer">by Daniela Grossmann, San Francisco, 2012</div>
   <nav>
      <ul id="nav_list_bottom" class="nav_list">
         <li><%= link_to "About",      about_path   %></li>
         <li><%= link_to "Contact",    contact_path   %></li>
      </ul>   
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="head_nav_wrap">
   <div id="head_nav">
      <div id="head">
         <%= link_to "My Tools Collection", root_path, id: "logo" %>
   </div>
      <nav id="nav">
         <ul id="nav_list_top" class="nav_list">
            <li><%= link_to "Home",       root_path %></li>
            <li><%= link_to "Help",       help_path %></li>

            <% if signed_in? %>
               <li><%= link_to "My Tools",   current_user %></li>
               <li><%= link_to "Settings",   edit_user_path(current_user) %></li> 
               <li><%= link_to "Sign out",   signout_path,  method: "delete" %></li>
            <% else %>
               <li><%= link_to "Sign in",    signin_path %></li>
            <% end %>
         </ul>
      </nav>
   </div>
   <h1 class="center title"><%= yield(:h1_title) %></h1>

   <% if signed_in? && current_user.admin? %>
      <nav id=nav_admin>
         <ul id="nav_list_admin" class="nav_list">
            <li><%= link_to "Edit Categories",  "#" %></li>
            <li><%= link_to "Edit Tools",       "#" %></li>
            <li><%= link_to "Edit Users",       users_path %></li>
         </ul>
      </nav>
   <% end %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
   <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= full_title(yield(:title)) %></title>

   <link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Lekton' rel='stylesheet' type='text/css'>

   <%= stylesheet_link_tag    "application", :media => "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>

   <%= render 'layouts/shim' %>

</head>
<body>
   <div id="wrapper">

      <%= render 'layouts/header' %>

      <div id="flash_messages">
         <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= "MyCollection: tools$ #{yield(:footer_title)} #{key.upcase}" %><br /><%= value %></div>
         <% end %>
      </div>

      <div class="container">
         <%= yield %>
      </div>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

   </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
   <div class="error_messages">
      <div class="alert alert-error form_message">
         <%= "MyCollection: tools$ #{yield(:footer_title)} #{pluralize(@user.errors.count, "ERROR").upcase}" %>
         <ul>
            <% target.errors.full_messages.each do |msg| %>
               <li>>> <%= msg %></li>
            <% end %>
         </ul>
      </div>
   </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:h1_title, "About") %>
<% provide(:footer_title, "about") %>

<p>
Assumenda accusamus commodo, next level master cleanse ea skateboard american apparel single-origin coffee photo booth pour-over. Organic dreamcatcher placeat, ex cray tempor wolf echo park keytar umami. Twee delectus freegan vice laboris ullamco. Sapiente cillum scenester, 8-bit mcsweeney's twee post-ironic +1 excepteur put a bird on it proident. Squid williamsburg chambray brooklyn. Mustache in aesthetic, marfa viral nihil mumblecore quis messenger bag portland. Iphone aliquip raw denim, excepteur food truck kogi umami occupy.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:h1_title, "Contact") %>
<% provide(:footer_title, "contact") %>

<p>
Hamburger mollit ham flank, deserunt tri-tip sunt excepteur. Cillum laborum short ribs cow andouille, venison fatback ham officia duis strip steak sunt. Turducken ribeye ullamco, biltong bresaola ground round pariatur pork leberkas ham. Sed ut ut capicola elit id, prosciutto adipisicing labore drumstick. Magna corned beef ham in. Shoulder excepteur ut kielbasa pariatur pastrami. Consectetur commodo nulla capicola culpa biltong sausage, consequat tempor incididunt tri-tip.


</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<% provide(:h1_title, "Need help?") %>
<% provide(:footer_title, "help_me") %>

<p>
   Swag gentrify gluten-free, +1 DIY wolf fap ennui. Street art seitan you probably haven't heard of them dreamcatcher, quinoa next level narwhal fanny pack. Pork belly seitan viral, cardigan direct trade fanny pack squid master cleanse pop-up keffiyeh. Mumblecore artisan cosby sweater bicycle rights viral, wolf street art bushwick you probably haven't heard of them keytar trust fund blog high life Austin pickled. Occupy sriracha quinoa, mcsweeney's whatever forage hella fixie authentic american apparel terry richardson blog mustache odd future PBR. Truffaut scenester tattooed, butcher VHS pitchfork narwhal twee brunch lo-fi wayfarers wolf pickled. Pork belly art party scenester vegan bushwick tattooed food truck, beard pinterest.

</p>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>
<% provide(:h1_title, "My Tools Collection") %>
<% provide(:footer_title, "my_tools_collection") %>



<p>
Pot ipsizzle that's the shizzle sizzle amizzle, crunk ass shiznit. I'm in the shizzle sapien velit, shit volutpizzle, suscipizzle daahng dawg, cool vizzle, its fo rizzle. Pellentesque eget tortizzle. Sizzle erizzle. Fusce izzle dolizzle get down get down fo shizzle tellivizzle uhuh ... yih!. Maurizzle pellentesque da bomb shit turpis. Break it down izzle tortor. Pellentesque eleifend crunk the bizzle. In shizzlin dizzle habitasse platea dictumst. Its fo rizzle dapibus. Curabitizzle tellizzle urna, fo shizzle dawg, mattizzle sheezy, shizzlin dizzle vitae, nunc. Shizzlin dizzle izzle. Integer shiznit shit sed break yo neck, yall.
<p>

<div class="button_center">
   <%= link_to "Sign up!", signup_path, class: "button1 center" %>
</div>

</p>
Praesent nizzle turpis ut leo bibendum molestie. Vivamus vestibulum tortor vizzle massa. Quisque malesuada ornare dawg. Morbi cool, nisl nec bibendum fo shizzle, magna dolor vestibulizzle ligula, ac mofo black things quis augue. Maecenas check it out elizzle fizzle bling bling its fo rizzle brizzle sagittizzle. Fo shizzle things pede ut lacizzle. In rhoncus nonummy fo. Fo shizzle ipsizzle dolizzle yo cool, consectetizzle adipiscing gangster. Fo shizzle izzle pimpin', posuere dawg amizzle, facilisis sed, fo mattis, libero. Gangsta sempizzle faucibus crazy. Ut break yo neck, yall stuff. Check it out fo shizzle mah nizzle fo rizzle, mah home g-dizzle funky fresh a crazy you son of a bizzle crazy. Shut the shizzle up crackalackin metus ghetto nunc. Aenean sodalizzle, ass black varius ma nizzle, fo shizzle cool fizzle felis, nec fo shizzle boofron nisl bizzle check it out. Sheezy crunk quam, crunk sizzle amizzle, owned yippiyo, pulvinar pulvinizzle, check it out.
</p>

app/views/users/_fields.html.erb
<%= f.label :name %><br />
<%= f.text_field :name %><br />

<%= f.label :email %><br />
<%= f.text_field :email %><br />

<%= f.label :password %><br />
<%= f.password_field :password %><br />

<%= f.label :password_confirmation, "Confirm Password" %><br />
<%= f.password_field :password_confirmation %><br /><br />

app/views/users/_user.html.erb
<li>
   <%= gravatar_for user %>
   <div class="index_name index"><%= link_to user.name, user %></div>

   <% if current_user.admin? %>
      <div class="index_mail index"><%= mail_to(user.email, image_tag("mail.png")) %></div>
      <div class="index_created index"><%= user.created_at.strftime("%Y-%m-%d") %></div>
      <div class="index_updated index"><%= user.updated_at.strftime("%Y-%m-%d") %></div>
   <% end %>
   <% if current_user.admin? && !current_user?(user) %>
      <div class="index_delete index"><%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %></div>
   <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:h1_title, "Update your profile") %>
<% provide(:footer_title, "update_profile") %>

<%= render 'shared/error_messages', :target => @user %>

<div class="form center" id="edit_form">

   <%= form_for(@user) do |f| %>
   
      <%= render 'fields', f: f %>

      <%= f.submit "Save changes", class: "button1 edit_button" %>

      <div id="picture_edit">
         <%= gravatar_for @user %>
         <a href="http://gravatar.com/emails" target="_blank">change</a>
      </div>

   <% end %>

</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<% provide(:h1_title, "All users") %>
<% provide(:footer_title, "all_users") %>

<div id="index_head">
   <%= will_paginate @users %>
   <% if current_user.admin? %>
      <p id="head_created">User since:</p>
      <p id="head_updated">Last update:</p>
   <% end %>
</div>

<ul class="users">
   <%= render @users %>
</ul>

<%= will_paginate @users %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:h1_title, "Sign up") %>
<% provide(:footer_title, "sign_up_please") %>


<%= render 'shared/error_messages', :target => @user %>

<div class="form center" id="sign_up_form">

   <%= form_for(@user) do |f| %>
   
      <%= render 'fields', f: f %>

      <%= f.submit "Create my account", class: "button1 sign_up_button" %>

   <% end %>

</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}'s Tools") %>
<% provide(:h1_title, "#{@user.name}'s Tools") %>
<% provide(:footer_title, "#{@user.name.downcase}s_tools") %>

<div id="user_left">
   <p id="user_picture"><%= gravatar_for @user %></p>
   <p id="user_name"><%= @user.name %></p>
</div>

<div id="user_right">
   <p>
      Cras auctor tortor feugiat augue aliquet mollis. Nam ullamcorper mi et odio porta posuere. Nam consequat egestas metus, et dignissim purus eleifend at. Nunc quis eros at lectus imperdiet dignissim quis sit amet magna. Aliquam erat volutpat. Aenean accumsan imperdiet tincidunt. Vestibulum facilisis auctor nisl, ut fermentum leo scelerisque a. Nulla euismod lorem lacus, eu vehicula metus. Maecenas eget nisl ut ipsum consequat luctus vitae ultricies eros. Vivamus condimentum ultrices ante ut elementum.
   </p>
   <p>
      Curabitur dapibus lorem nec lacus scelerisque in posuere quam pharetra. Mauris a tellus a massa dictum porta at vitae lorem. Donec ac lectus ac sapien congue gravida. In hac habitasse platea dictumst. Nam at urna eu sem pellentesque facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Donec sed est vitae nunc vehicula imperdiet at quis risus. Curabitur quis sapien mi, et molestie velit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse auctor ipsum ac nunc pulvinar aliquet. In euismod metus id metus rhoncus facilisis.
   </p>
</div>